In [1]:
import pandas as pd
data = pd.read_csv("p2c-attempts-v1.csv")
data2 = data.replace('A01', 1).replace('A02', 2).replace('A03', 3)
print(data2.dtypes)

student            int64
assignment         int64
attempt            int64
grade              int64
submission time    int64
dtype: object

In [9]:
#data3 = data2.sort_values("student")
data3 = data2.sort_values(['student', 'assignment', "attempt"])
data3.head(10)

      student  assignment  attempt  grade  submission time
1082    10133           1        1     85               35
1442    10133           1        2     81               32
385     10133           1        3     81               34
627     10133           1        4     97               35
1923    10133           1        5     88                7
984     10133           2        1     50               32
1231    10133           2        2     96               32
1877    10133           3        1     81                4
1909    10133           3        2    100                2
457     10406           1        1     74               48

In [6]:
for i in data3["student"]:
    print(i)

10133
10133
10133
10133
10133
10133
10133
10133
10133
10406
10884
10884
10884
10884
10884
10884
10884
10884
10884
10884
10884
10884
10884
11409
11409
11409
11873
11873
11873
11873
11873
11873
11873
11873
11873
11873
11873
12472
12472
12472
12472
12481
12481
12481
12481
13512
13512
13512
13512
13512
13512
13819
13819
13819
13819
13819
13819
13819
13819
13857
13857
13857
13857
13857
13857
14107
14107
14107
14533
14533
14533
14533
14533
14533
14533
14533
14533
14533
14533
14533
14840
14840
14937
15458
15458
15458
15458
15528
15528
15528
15528
15528
15528
15528
15541
15541
15541
15771
15771
15771
15771
15771
15771
15771
15771
15771
15771
15771
16284
16284
16284
16322
16322
16322
16322
16322
16940
16940
16940
16940
16940
16940
17497
17497
17497
17497
17497
17497
17497
17668
17668
17668
17668
17668
17668
17692
17692
17692
17692
17692
17692
17692
17692
17692
17836
17836
17836
17836
17851
17851
17851
17851
17851
18208
18208
18208
18208
18208
18208
18208
18306
18306
18306
18306
18306
18306
18306
18306
18402
18402
18402
18402
18402
18402
18402
18526
18526
18526
18526
18526
18526
19005
19005
19005
19005
19005
19005
19005
19005
19005
19005
19005
19005
19005
19005
19005
19005
19005
19005
19005
19005
19005
19005
19005
19041
19041
19041
19041
19041
19041
19041
19041
19041
19041
19041
19041
19041
19062
19062
19062
19062
19062
19062
19062
19062
19062
19591
19591
19591
19591
19591
19591
19591
19591
19863
19863
19863
19863
19863
19863
19873
19873
19873
19873
19873
19873
19873
19873
19873
19873
19873
19873
19873
19873
19873
19873
19873
19873
19873
19873
19873
19910
19910
19910
20216
20216
20216
20216
20216
20216
20216
20216
20468
20468
20468
20468
20468
20468
20468
20468
20468
20627
20627
20627
21476
21476
21476
21476
21476
21476
21476
21476
21476
21476
21476
21476
21476
21476
21476
21476
21476
21476
21476
21476
21476
21476
21476
22751
22751
22751
22751
22751
22751
22751
22751
22751
22751
22751
22751
22751
23055
23055
23055
23055
23055
23055
23055
23172
23172
23172
23172
23172
23172
23172
23172
23172
23172
23172
23666
23666
23666
23666
23666
24386
24386
24386
24386
24386
24386
24386
24386
24386
24386
24386
24386
24386
24697
24697
24697
24697
24697
24697
24697
25848
25848
25848
25848
25848
25848
25848
25873
25873
25873
25873
25873
25873
25873
25873
26099
26099
26099
26099
26099
26099
26099
26099
26099
26168
26168
26168
26168
26168
26168
26263
26263
26263
26263
26263
26263
26263
26263
26263
26263
26375
26375
26375
26375
26375
26375
26375
26375
26375
26996
26996
26996
26996
26996
26996
26996
26996
27545
27545
27545
27545
27545
27545
27545
27545
27545
27545
27545
28118
28118
28118
28118
28118
28118
29397
29397
29397
29397
29397
29397
29397
29397
29397
29414
29414
29414
29414
29414
29414
29414
29866
30122
30122
30122
30122
30269
30269
30269
30269
30269
30269
30269
30269
30269
30269
30269
30269
30269
30269
30269
30269
30269
30269
30269
30269
30269
30596
30596
30596
30596
30596
30989
30989
30989
30989
30989
30989
30989
30989
30989
30989
30989
31251
31251
31251
31251
31251
31379
31379
31379
31379
31379
31379
31379
31379
31379
31379
31379
31379
31379
31379
31379
31379
31570
31570
31570
31570
31570
31687
31687
31687
31687
31687
31687
31687
31787
31787
31787
32092
32092
32092
32092
32092
32092
32092
32348
32348
32348
32348
32348
32348
32348
32348
32348
32348
32348
33179
33179
33179
33179
33179
33179
33179
33179
33179
33179
33490
33490
33490
33490
33490
33490
33490
33490
33791
33791
33791
33791
33791
33791
33791
33954
33954
33954
33954
34047
34047
34047
34226
34226
34226
34226
34226
34226
34226
34226
34226
34285
34285
34963
34963
34963
34963
34963
34963
34963
34963
34963
34963
34963
34963
34963
35099
35099
35099
35099
35099
35099
35099
35099
35099
35099
35099
35099
35099
35443
35443
35443
35443
35443
35443
35716
35716
35716
35716
35716
35716
35716
35716
35716
35817
35817
35817
35817
35817
35817
36776
36776
36776
36776
36776
36776
36914
36914
36914
36914
36914
36914
36914
36914
36914
36914
36914
37119
37119
37119
37119
37119
37119
37119
37119
38048
38048
38048
38048
38048
38261
38261
38261
38261
38261
38261
38615
38615
38615
38615
38932
38932
38932
38932
39612
39612
39612
39612
39612
39612
39612
39908
39908
39908
39908
39908
39908
40835
40835
40835
40835
40835
40835
40835
40923
40923
40923
40923
40923
40923
40923
40923
40923
40923
40923
41502
41502
41502
42798
42798
43025
43025
43025
43503
43503
43503
43503
43503
43503
43503
43503
43503
43503
43503
43586
43586
43586
43586
43586
43586
43586
44005
44005
44005
44005
44005
44005
44005
44005
44005
44069
44069
44069
44069
44069
44069
44069
44069
44069
44169
44169
44729
44729
44729
44853
44853
44853
44853
44853
44853
45097
45097
45097
45097
45097
45097
45097
45097
45097
45225
45225
45225
45225
45225
45225
45225
45225
45225
45225
45225
45285
45285
45285
45418
45418
45418
45418
45418
45418
45418
45420
45420
45420
45420
45748
45748
45748
45748
45748
45748
45748
45748
45748
45748
45748
45748
45748
45748
45748
45748
45748
45748
45748
45927
45927
45960
45960
45960
45960
45960
46193
46193
46193
46193
46193
46193
46514
46514
46514
46514
47148
47148
47148
47148
47148
47148
47148
47148
47148
47148
47148
47148
47148
47148
47148
47148
47468
47468
47468
47468
47468
47468
47580
47580
47580
47931
47931
47931
47931
47931
48562
48562
48562
49013
49013
49013
49013
49013
49013
50361
50361
50361
50361
50543
50543
50543
50543
50543
50543
50543
50543
50543
50671
50671
50671
50745
50745
50745
50907
50907
50907
50907
50907
50907
50907
50907
51025
51025
51025
51025
51025
51822
51822
51822
51822
51822
51822
51822
52655
52655
52655
52655
52655
52655
52655
52655
52655
52859
52859
52859
52859
52859
52859
52859
52859
52859
52859
52859
52859
53370
53370
53370
53370
53370
53370
53370
53370
53370
53650
53650
53650
53650
53650
53650
53650
53650
53650
53650
53650
53834
53834
53834
53834
53834
53834
54196
54196
54196
54196
54196
54196
54196
54196
54454
54454
54454
54454
54454
54472
54472
54472
54472
54472
54472
55090
55090
55090
55090
55090
55090
55090
55090
55143
55143
55143
55143
55143
55243
55243
55243
55243
55243
55243
55351
55351
55351
55351
55351
55351
55690
55690
55690
55690
55690
55690
55690
56194
56194
56194
56194
56194
56194
56194
56739
56739
56739
56739
56739
56739
56739
57270
57270
57270
57270
57270
57270
57270
57380
57380
57380
57380
57380
57982
57982
57982
57982
57982
59819
59819
59819
59819
59819
59819
59819
59819
59819
59819
59819
59819
59819
59819
59819
59819
59819
59819
59819
59819
59819
60064
60064
60064
60064
60064
60064
60064
60064
60064
60064
60064
60307
60307
60307
60307
60343
60343
60343
60343
60955
60955
60955
60955
60955
60955
60955
60955
60955
60955
60955
60955
60972
60972
60972
60972
60972
60972
60984
60984
60984
60984
60984
60984
60984
60984
61237
61237
61237
61237
61237
61237
61237
61237
61237
61237
61237
61237
61237
61237
61237
61237
61237
61237
61454
61454
61454
61454
61454
61454
61454
61454
61454
61454
61454
61701
61701
61701
61701
61701
61701
61701
61701
61701
61701
61701
61701
61701
61701
61701
61701
61701
61701
61701
61701
61701
62250
62250
62250
62250
62250
62250
62250
62250
62250
62250
62250
62250
62250
62250
62250
62250
62250
62250
62250
62250
62250
62702
62702
62702
62702
62702
62702
63045
63045
63045
63045
63045
63045
63335
63335
63335
63335
63335
63445
63445
63445
63445
63445
63445
63445
63974
63974
63974
63974
63974
63974
63974
64395
64395
64395
64395
64395
64395
64773
64773
65229
65229
65229
65229
65303
65303
65303
65303
65303
65303
65303
65303
65303
65564
65564
65564
65769
65769
65769
65769
65769
65769
65769
65937
65937
65937
65937
65937
65937
65937
65937
65937
65937
66144
66144
66144
66144
66144
66144
66144
66144
66144
66156
66156
66156
66156
66156
66156
66156
66156
66156
66156
66205
66205
66205
66205
66205
66205
66205
66205
66213
66213
66213
66495
66495
66495
66495
66495
66495
66495
67003
67003
67003
67003
67003
67003
67003
67604
67604
67736
67736
67736
67736
67736
67736
67736
68076
68076
68076
68076
68076
68076
68076
68076
68113
68113
68402
68402
68402
69402
69402
69402
69402
69402
69402
69402
69402
69402
69644
69644
69644
69644
69644
69644
69644
69644
69644
69644
69644
69644
69644
69644
69644
69644
69644
69644
69644
69644
69644
69644
69644
69644
69749
69749
69749
69749
69749
69749
70201
70201
70201
70201
70201
70201
70201
70201
70201
71843
71843
71843
71843
71843
71843
71843
72887
72887
72887
72887
72887
72887
72887
72887
72887
72887
72887
72887
72887
74801
74801
74801
74801
74801
74801
74801
74801
74801
74801
74801
74801
74801
74801
74801
74801
74801
74801
74801
74801
74801
74928
74928
74928
74928
74928
74928
74928
74928
74969
74969
74969
77180
77180
77180
77180
77180
77180
77180
77180
77180
77670
77670
77670
77670
77670
77747
77747
77747
77946
77946
77946
77946
77946
77946
78160
78160
78160
78476
78476
78476
78476
78476
78476
78476
78476
78476
78476
78575
78575
78575
78575
78575
78575
78749
78749
78749
78884
78884
78884
78884
78884
78884
79038
79038
79038
79243
79243
79243
79243
79243
79243
79243
79243
79243
79243
79243
79243
79243
79243
79243
79243
79300
79300
79300
79300
79398
79398
79398
79398
79398
79398
80429
80429
80429
80429
80429
80545
80545
80545
80545
80545
80545
80758
80758
80758
80758
80758
80758
80758
82252
82252
82252
82252
82252
82252
82252
82705
82705
82705
82705
82705
82815
82815
82815
82815
82815
82815
82815
83185
83185
83204
83204
83204
83204
83204
83204
83216
83216
83216
83216
83410
83410
83410
83410
83410
83410
83832
83832
83832
83832
83832
83832
83832
83832
83977
83977
83977
84900
84900
84900
84900
84900
84900
84900
84900
84900
84998
84998
84998
84998
84998
84998
84998
84998
84998
84998
84998
85058
85058
85058
85058
85058
85058
85058
85058
85058
85058
85058
85058
85058
86077
86077
86274
86274
86274
86274
86732
86732
86732
86732
86732
86732
86732
86732
86732
86732
86732
86732
86732
86732
86732
86732
86732
86732
86732
86732
86732
86732
86732
86825
86825
86825
86956
86956
86956
86956
86956
86956
86956
86956
86956
86956
86956
86956
86956
86956
86956
86956
86956
86956
87115
87115
87115
87304
87304
87304
87304
87304
87304
88304
88304
88304
88304
88304
88304
88304
88304
88304
88677
88677
88677
88741
88741
88741
88741
88741
88741
88788
88788
88788
88788
88788
88788
88788
88788
88788
88788
88788
88788
88788
88788
88788
88788
88788
88788
88788
88788
88788
88788
88788
88788
89018
89018
89018
89018
89232
89232
89232
89623
89623
89623
89623
89623
89623
90439
90439
90439
90439
90439
91537
91537
91537
91537
91537
91537
91537
91537
91537
91537
91537
91537
91537
91537
91537
91537
91537
91537
91537
91537
91537
91537
91537
91537
91888
91888
91888
91888
91888
91888
91888
92089
92089
92089
92089
92329
92329
92329
92329
92329
92329
92329
92329
92329
92329
92329
92329
92329
92329
92329
92329
92329
92329
92329
92431
92431
92431
92431
92431
92431
93085
93085
93085
93085
93696
93696
93696
93696
93696
93696
93696
93696
93696
93696
93696
93696
93696
93696
93696
93696
93696
93696
93696
93741
93741
93741
93741
93814
93814
93814
93814
93814
93814
93814
93852
93852
93852
93852
93852
93852
93907
93907
93907
93907
93907
94213
94213
94213
94213
94213
94213
94213
94213
94213
94213
94213
94213
94213
94289
94289
94289
94289
94289
94289
94372
94372
94372
94372
94372
94559
94559
94559
94559
94559
94559
94559
94559
94559
94559
95172
95172
95172
95172
95172
95172
95172
95172
95172
95172
95172
95382
95382
95382
95382
95382
95382
95903
95903
95903
95903
95903
95903
95903
95903
96110
96110
96110
96110
96110
96110
96155
96155
96155
96155
96155
96155
96155
96155
96155
96274
96274
96274
96274
96274
96274
96274
96274
96274
96308
96308
96308
96308
96308
96308
96308
96308
96308
96308
96308
96308
96308
96308
96308
96308
96308
96308
96443
96443
96443
96443
96443
96543
96543
96543
96543
96543
96543
96665
96665
96665
96665
96665
96732
96732
96732
96732
96732
96732
96732
96732
97979
97979
97979
97979
97979
97979
97979
98255
98255
99101
99101
99101
99140
99140
99140
99140
99140
99858
99858

In [28]:
data4 = data3[:9]
latesub_weight = 0.6
gradeimprovement_weight = 0.4
procrastintion_attempts = 0

for i in data4["submission time"]:
    if i < 0:
        procrastintion_attempts += 1

assignment1_gradeimprov = 0
assignment2_gradeimprov = 0
assignment3_gradeimprov = 0

In [20]:
data4

      student  assignment  attempt  grade  submission time
1082    10133           1        1     85               35
1442    10133           1        2     81               32
385     10133           1        3     81               34
627     10133           1        4     97               35
1923    10133           1        5     88                7
984     10133           2        1     50               32
1231    10133           2        2     96               32
1877    10133           3        1     81                4
1909    10133           3        2    100                2